name: tests
on:
  pull_request:
  push:
    branches: [main, feat/test-action-on-push]
    paths-ignore:
      - "**.md"

  schedule:
    - cron: "0 6 * * *"

  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: Debug with tmate
        default: false

permissions:
  actions: write

jobs:
  tests:
    strategy:
      matrix:
        ddev_version: [stable, HEAD]
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      - uses: julienloizelet/ddev-add-on-test@20a7c1489181dae10ce6af9b0680899e2f33c8a2
        with:
          ddev_version: ${{ matrix.ddev_version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          debug_enabled: ${{ github.event.inputs.debug_enabled }}
          addon_repository: ${{ env.GITHUB_REPOSITORY }}
          addon_ref: ${{ env.GITHUB_REF }}
